log_level = "info"

[router]
host = "172.16.0.1"
username = "monitor"
password = "Monitor5103"

[monitor]
interval = 15
url = "https://www.gstatic.com/generate_204"
timeout = 10
max_retries = 4
min_reboot_interval = 3600
